name: Go Checks

on:
  push:
  pull_request:

jobs:

  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go mod download
    - name: Test
      run: go test -cover ./...

  build:
    runs-on: ubuntu-latest
    needs: testing
    if: contains(github.ref, 'master')
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lol3r/random-wikipedia-backend:${{ env.GITHUB_SHA }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'master')
    steps:
      - name: Deploy to Cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/random-wikipedia-backend random-wikipedia-backend=$GITHUB_SHA
